[package]
name = "codewars-bot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "A Slack bot to report Codewars statistics"

[dependencies]
anyhow = "1.0.28"
async-trait = "0.1.30"
bytes = "0.5.4"
chrono = { version = "0.4.11", features = ["serde"] }
console = { version = "0.11.2", default-features = false }
dotenv = "0.15.0"
fern = "0.6.0"
futures = "0.3.4"
hex = "0.4.2"
hmac = "0.7.1"
humantime = "2.0.0"
log = { version = "0.4.8", features = ["release_max_level_trace"] }
once_cell = "1.3.1"
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
sha2 = "0.8.1"
structopt = "0.3.14"
thiserror = "1.0.16"
tokio = { version = "0.2.20", features = ["fs", "macros", "rt-core", "signal", "stream", "sync"] }
toml = "0.5.6"
url = { version = "2.1.1", features = ["serde"] }
warp = { version = "0.2.2", default-features = false }

[dependencies.reqwest]
version = "0.10.4"
default-features = false
features = ["gzip", "json", "rustls-tls"]

[dev-dependencies]
env_logger = { version = "0.7.1", default-features = false }
tempfile = "3.1.0"

[profile.release]
lto = true
panic = "abort"
