[package]
name = "codewars-bot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.26"
chrono = { version = "0.4.10", features = ["serde"] }
console = "0.9.2"
dotenv = "0.15.0"
fern = "0.5.9"
futures = "0.3.4"
log = "0.4.8"
once_cell = "1.3.1"
pest = "2.1.2"
pest_derive = "2.1.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
structopt = "0.3.9"
thiserror = "1.0.11"
tokio = { version = "0.2.11", features = ["fs", "macros", "rt-core", "signal", "stream", "sync"] }
toml = "0.5.6"
url = { version = "2.1.1", features = ["serde"] }
warp = { version = "0.2.1", default-features = false }

[dependencies.reqwest]
version = "0.10.1"
default-features = false
features = ["gzip", "json", "rustls-tls"]

[dev-dependencies]
tempfile = "3.1.0"

[profile.release]
lto = true
panic = "abort"
