[package]
name = "codewars-bot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
chrono = { version = "0.4.10", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.4"
once_cell = "1.3.1"
reqwest = { version = "0.10.1", features = ["gzip", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
tokio = { version = "0.2.11", features = ["macros", "rt-core"] }
tokio-tungstenite = { version = "0.10.1", features = ["tls"] }
url = { version = "2.1.1", features = ["serde"] }

[profile.release]
lto = true
panic = "abort"
