[package]
name = "codewars-bot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "A Slack bot to report Codewars statistics"

[dependencies]
anyhow = "1.0.31"
async-trait = "0.1.36"
bytes = "0.5.6"
chrono = { version = "0.4.13", features = ["serde"] }
dotenv = "0.15.0"
fern = "0.6.0"
futures = "0.3.5"
hex = "0.4.2"
hmac = "0.8.1"
humantime = "2.0.1"
log = { version = "0.4.8", features = ["release_max_level_trace"] }
once_cell = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
sha2 = "0.9.1"
thiserror = "1.0.20"
toml = "0.5.6"
url = { version = "2.1.1", features = ["serde"] }
warp = { version = "0.2.3", default-features = false }
yansi = "0.5.0"

[dependencies.config]
version = "0.10.1"
default-features = false
features = ["toml"]

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["gzip", "json", "rustls-tls"]

[dependencies.tokio]
version = "0.2.21"
features = ["fs", "macros", "rt-threaded", "signal", "sync"]

[dev-dependencies]
env_logger = { version = "0.7.1", default-features = false }
tempfile = "3.1.0"

[profile.release]
lto = true
panic = "abort"
