[package]
name = "codewars-bot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.26"
chrono = { version = "0.4.10", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.4"
log = "0.4.8"
once_cell = "1.3.1"
pest = "2.1.2"
pest_derive = "2.1.0"
pretty_env_logger = "0.4.0"
reqwest = { version = "0.10.1", features = ["gzip", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
tokio = { version = "0.2.11", features = ["macros", "rt-core", "sync"] }
tokio-tungstenite = { version = "0.10.1", features = ["tls"] }
url = { version = "2.1.1", features = ["serde"] }

[profile.release]
lto = true
panic = "abort"
